site_name: Документация лабораторных работ
site_description: Документация по лабораторным работам по веб-разработке

nav:
  - Главная: index.md
  - Лабораторная работа №1: lab1.md
  - Лабораторная работа №2: lab2.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

